name: Build

on:
  push:
    branches:
      - "*"

jobs:
  main:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DATABASE: booktown

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check Formatting
        run: ./script/check_formatting.sh

      - name: Check Assets
        run: ./script/check_assets.sh

      - name: Setup
        run: make setup

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Test All
        run: make test-all

      - name: Docker Release
        run: make docker-release